### ISSUE TITLE
Is FeatGraph still work when using mini-batch for gnn training?

### ISSUE THREAD

**Issue by maqy1995** [amazon-research/FeatGraph#5]
the paper said:
> FeatGraph generates kernel codes for a specific graph topology (i.e., the adjacency matrix);

if we use mini-batch for GNN training, the subgraph structure corresponding to each batch should be uncertain in this case. Is FeatGraph still work?

**Comment by yzh119** [comment]
FeatGraph achieves its best performance when graph structure is fixed.
When graph topology changes over time (say mini-batch training), FeatGraph still works if we remove the graph partitioning phase and it would harm performance. JIT for mini-batch training is still a open problem.

**Comment by maqy1995** [comment]
@yzh119 , thank you for your reply.
In other words, in this case, the optimization strategy obtained through FDS is still effective? And FDS is actually optimized through tvm, right?

In addition, I noticed that DGL 0.6 has been released. Has FeatGraph been used in some models (such as GAT)? Or is there a tutorial on how to use it?

**Comment by yzh119** [comment]
Yes FDS still works.
For DGL 0.6, however, there are some existing bugs in TVM that impeding us from relying on featgraph: https://github.com/apache/tvm/issues/6596, we are still waiting for the landing of TVM's new IR: tir to address the issue.
Actually, we have already used some optimizations proposed in featgraph paper (e.g. tree reduction for sddmm) and GAT's speed in DGL 0.6 is much better than DGL 0.4 (when featgraph paper released).

**Comment by maqy1995** [comment]
get, thanks again.
