### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Dibbya40** [amazon-research/FeatGraph#8]
num_cuda_blocks: 64
num_threads_per_cuda_block: 32
Traceback (most recent call last):
  File "bench_vanilla_spmm.py", line 84, in <module>
    bench_vanilla_spmm_cuda(adj_scipy_csr, args.feat_len)
  File "bench_vanilla_spmm.py", line 68, in bench_vanilla_spmm_cuda
    _bench_vanilla_spmm_cuda(num_cuda_blocks, num_threads_per_cuda_block)
  File "bench_vanilla_spmm.py", line 49, in _bench_vanilla_spmm_cuda
    vanilla_spmm_module = VanillaSpMMcuda(adj_scipy_csr)
  File "/home/dsaha/FeatGraph/python/featgraph/module/spmm.py", line 214, in __init__
    super(VanillaSpMMcuda, self).__init__(adj_scipy, num_col_partitions=1)
  File "/home/dsaha/FeatGraph/python/featgraph/module/spmm.py", line 67, in __init__
    self._adj_indptr_tvm = tvm.nd.array(self._adj_indptr, ctx=self._ctx)
TypeError: array() got an unexpected keyword argument 'ctx'

I am getting this error when I run "python3 bench_vanilla_spmm.py --dataset data/reddit_csr_float32.npz --feat-len 64 --target cuda". Could you help me?

**Comment by yzh119** [comment]
Which version of tvm you were using?

**Comment by Dibbya40** [comment]
> Which version of tvm you were using?

0.8.dev0

**Comment by Huyuwei** [comment]
@Dibbya40 could you try tvm v0.7? We did the experiments with that version.

**Comment by Dibbya40** [comment]
> @Dibbya40 could you try tvm v0.7? We did the experiments with that version.

Thank you so much. Did you use this one  (git clone --recursive https://github.com/apache/incubator-tvm tvm) for tvm v0.7?

**Comment by Huyuwei** [comment]
Use `git clone -b v0.7 --recursive https://github.com/apache/incubator-tvm tvm`

**Comment by Dibbya40** [comment]
Hello. I am using tvm v0.7 now but when I run the benchmark scripts, it gives me this error:

File "bench_vanilla_spmm.py", line 7, in <module>
    from tvm.topi.utils import get_const_tuple
ModuleNotFoundError: No module named 'tvm.topi.utils'

Could you please help me?

**Comment by Huyuwei** [comment]
This issue is solved by #10

**Comment by Dibbya40** [comment]
Thank you so much @Huyuwei . It worked, but now I am getting **TVMError: Check failed: bf != nullptr: target.build.llvm is not enabled**.

**Comment by Huyuwei** [comment]
You need to install TVM with LLVM enabled. https://tvm.apache.org/docs/install/from_source.html

Confirm that you have successfully installed TVM by running this tutorial: http://tvm.apache.org/docs/tutorials/get_started/tensor_expr_get_started.html

**Comment by Dibbya40** [comment]
Thank you so much @Huyuwei. It works now.
